### ISSUE TITLE
Version Control for Workflows

### ISSUE THREAD

**Issue by DavidtheGoliath** [Shuffle/Shuffle#1104]
Could we have version control for workflows, the issue arises when collaborating and someone made changes to a W.F and the changes made cause an issue in the workflow and you quickly need to revert back to the initial flow that you had. Instead of having to so it all over.

**Comment by frikky** [comment]
- Workflows should be workable by multiple people
- Multiple people working on workflows causes "overwrites" of the same item
- Saving a workflow should keep a backup of the old version(s) to load

In short:
- Make a button where you can see old versions of a Workflow and choose from them. 
![image](https://github.com/Shuffle/Shuffle/assets/5719530/b3669b9a-c6ce-4c43-8f88-191e6415aa46)

**Comment by frikky** [comment]
API should be available from next week to start testing: `/api/v1/workflows/{workflow_id}/revisions`

This stores revisions based on changes to actions/triggers/variables, and will for now keep ALL of them. We will probably make it max out at a certain point, but this is a good start.

For the frontend: The point will probably be to be able to jump between them. That's why the API is RAW loading in all the workflows, meaning you in practice can "quick swap" to another workflow. Frontend should make it possible to click an old workflow, which unloads the old workflow (after asking if they want to save) and loads in the new into the UI directly.

**Comment by frikky** [comment]
This has now been added, and is available on shuffler.io and in the next nightly :)
