### ISSUE TITLE
Import Workflow problem: Always translate to default environment

### ISSUE THREAD

**Issue by frikky** [Shuffle/Shuffle#1175]
When importing a workflow, always set the environment for all nodes to the DEFAULT of the organization that imported it.

**Comment by TPower2112** [comment]
Can you import workflows from other vendors such as Tines? or is it importing other Shuffle workflows?  
Thx.
TP

**Comment by frikky** [comment]
> Can you import workflows from other vendors such as Tines? or is it importing other Shuffle workflows? Thx. TP

Not yet sadly! Shuffle is working on getting to support of CACAO however, as to make interoperability easier. Is it a complex workflow you're trying to transfer?

**Comment by TPower2112** [comment]
No, it's a simple workflow.  It's a Tines POC workflow we did.  An analyst can use a webform to add one IOC or upload a csv of IOCs, so that Tines can push them to CrowdStrike IOC Management.

We have a more complex phishing email analysis/ServiceNow workflow, but I wanted to work with a simple workflow first to understand Shuffle.

**Comment by frikky** [comment]
> No, it's a simple workflow. It's a Tines POC workflow we did. An analyst can use a webform to add one IOC or upload a csv of IOCs, so that Tines can push them to CrowdStrike IOC Management.
> 
> We have a more complex phishing email analysis/ServiceNow workflow, but I wanted to work with a simple workflow first to understand Shuffle.

Gotcha. We can't do this without a standardised format I'm afraid, so you'll have to build it out instead.

**Comment by 0x0elliot** [comment]
This was fixed and will be a part of 1.3.0.
