### ISSUE TITLE
Provide a Kubernetes alternative for mounting docker.sock

### ISSUE THREAD

**Issue by samling** [Shuffle/Shuffle#225]
I'm working on running Shuffle in our Kubernetes clusters. Since our clusters are configured to run Docker under the hood as their runtime, we are able to mount /var/lib/docker.sock into the Orborus pod as required. However, with the release of Kubernetes 1.20, Docker is no longer supported as a runtime in favor of directly using containerd, which means we will no longer have the ability to mount the docker socket.

It would be nice to be able to leverage native Kubernetes mechanisms to do what was previously done through the docker socket, i.e. use a service account API token to talk to the cluster and create the worker and app sdk pods. I noticed the documentation on the website describes a `RUNNING_MODE: kubernetes` variable, but it's unclear to me what that changes, as the requirement for docker.sock is still there.

**Comment by frikky** [comment]
Hey - this for sure needs clarification, so I'll try my best. Keep in mind I'm not a Kubernetes expert, but am aware of the 1.20 release and the limitations it puts on us.

1. The ```RUNNING_MODE: kubernetes``` feature was simply a way of getting containers to run in the same space using the "Orborus" mechanism. This requires containers to talk to each other, and it's just used to get a reference to another container. It won't do any good for what you're talking about. 
2. In general, we wouldn't want to support only Docker - this was just the simplest option when Shuffle was started. Because of our architecture which builds Docker containers directly using their API, there's no simple switch either. This is why the Docker socket is, and will for a while be required until we change the API's being used for building and downloading containers. 

I can't promise we'll fix this immediately, but as we start thinking more about scale (it's happening.. :) ), we'll for sure move to Kubernetes or similar tech over time. This means 2021 release sometime - after we've had our launch and such. I'm expecting the EOL for the previous versions of K8s to still be viable for quite a while. 

Always open to suggestions though, and this mainly comes down to what our focus is right now. If most of our userbase require Kubernetes, of course we'll move faster, but the number one priority right now is accessibility, not scale. Thanks! :fire:

**Comment by TheMatrix97** [comment]
Hi!
First of all @frikky, thanks for all the effort put into the project. 
Given the current technology landscape, I think K8s should be a priority in front of docker swarm, as companies are clearly shifting towards k8s. So, some questions are growing on me when trying to think in a good k8s solution:

1. Right now Orborus is creating containers in the K8s Docker socket. Given the fact that we reached 1.21 EOL (https://kubernetes.io/releases/patch-releases/#support-period), it doesn't seem viable stick to this mechanism
2. Also, deploying containers outside k8s control plane is a problem in terms of networking, we should be able to use K8s internal Services. Exposing the services as nodePorts just for internal service communications could be a potential security issue if the node is totally exposed... 
    ````bash
    F:\>docker logs 6e6d
    2022/07/07 16:40:42 [ERROR] Failed setting up Opensearch: dial tcp: lookup shuffle-opensearch on 192.168.65.5:53: no such host
    2022/07/07 16:40:42 [ERROR] Failed to run worker init: dial tcp: lookup shuffle-opensearch on 192.168.65.5:53: no such host
    2022/07/07 16:40:42 [INFO] Setting up worker environment
    2022/07/07 16:40:42 [INFO] Running with timezone Asia/Shanghai and swarm config ""
    2022/07/07 16:40:42 [INFO] Running normal execution with auth 8aa83c71-88ee-492a-baa9-deb0979e5b4e and ID bd77d2df-4702-4fba-b67f-07db75a18d0c
    2022/07/07 16:40:52 [ERROR] Failed request: Post "http://backend-service:5001/api/v1/streams/results": dial tcp: lookup backend-service on 192.168.65.5:53: read udp 172.17.0.5:38406->192.168.65.5:53: i/o timeout
    ````

So, It seems the easiest way to support new K8s versions passes through interacting with k8s api, instead the container engine socket. This way, we might be able to deploy Orborus worker pods as K8s Jobs (https://kubernetes.io/docs/concepts/workloads/controllers/job/), being totally connected to the k8s control plane.

What do you think? If you need help for testing and developing a solution, please let me know.

Thanks!

**Comment by frikky** [comment]
> Hi! First of all @frikky, thanks for all the effort put into the project. Given the current technology landscape, I think K8s should be a priority in front of docker swarm, as companies are clearly shifting towards k8s. So, some questions are growing on me when trying to think in a good k8s solution:
> 
> 1. Right now Orborus is creating containers in the K8s Docker socket. Given the fact that we reached 1.21 EOL (https://kubernetes.io/releases/patch-releases/#support-period), it doesn't seem viable stick to this mechanism
> 2. Also, deploying containers outside k8s control plane is a problem in terms of networking, we should be able to use K8s internal Services. Exposing the services as nodePorts just for internal service communications could be a potential security issue if the node is totally exposed...
>    ```shell
>    F:\>docker logs 6e6d
>    2022/07/07 16:40:42 [ERROR] Failed setting up Opensearch: dial tcp: lookup shuffle-opensearch on 192.168.65.5:53: no such host
>    2022/07/07 16:40:42 [ERROR] Failed to run worker init: dial tcp: lookup shuffle-opensearch on 192.168.65.5:53: no such host
>    2022/07/07 16:40:42 [INFO] Setting up worker environment
>    2022/07/07 16:40:42 [INFO] Running with timezone Asia/Shanghai and swarm config ""
>    2022/07/07 16:40:42 [INFO] Running normal execution with auth 8aa83c71-88ee-492a-baa9-deb0979e5b4e and ID bd77d2df-4702-4fba-b67f-07db75a18d0c
>    2022/07/07 16:40:52 [ERROR] Failed request: Post "http://backend-service:5001/api/v1/streams/results": dial tcp: lookup backend-service on 192.168.65.5:53: read udp 172.17.0.5:38406->192.168.65.5:53: i/o timeout
>    ```
> 
> So, It seems the easiest way to support new K8s versions passes through interacting with k8s api, instead the container engine socket. This way, we might be able to deploy Orborus worker pods as K8s Jobs (https://kubernetes.io/docs/concepts/workloads/controllers/job/), being totally connected to the k8s control plane.
> 
> What do you think? If you need help for testing and developing a solution, please let me know.
> 
> Thanks!

Heyo! Thanks for digging into it, and you are absolutely right. We want to support K8s fully, but the problem all along has been the fact that we started with Docker... and that it's been working, especially Swarm 

The problem isn't with what's mounted in, but the fact that Shuffle itself (Orborus & Worker) is using the Docker Go API's directly and acting as the orchestrators, rather than Docker doing all of that itself. This means ALL the Docker API's that are used in Orborus and the Worker will need to be translated (it's a lot): https://github.com/Shuffle/Shuffle/tree/master/functions/onprem

I encourage you to approach and develop it if you can, as we really can't prioritize it, and probably won't be able to until it's a necessity (1-2 years from now~). I'm up for a chat if you need some guidance on how to go about it

**Comment by TheMatrix97** [comment]
> The problem isn't with what's mounted in, but the fact that Shuffle itself (Orborus & Worker) is using the Docker Go API's directly and acting as the orchestrators, rather than Docker doing all of that itself. This means ALL the Docker API's that are used in Orborus and the Worker will need to be translated (it's a lot): https://github.com/Shuffle/Shuffle/tree/master/functions/onprem

I see... though it would be easier... I'll probably take a look at it in a near future. Thanks for the guidance :)

**Comment by frikky** [comment]
> > The problem isn't with what's mounted in, but the fact that Shuffle itself (Orborus & Worker) is using the Docker Go API's directly and acting as the orchestrators, rather than Docker doing all of that itself. This means ALL the Docker API's that are used in Orborus and the Worker will need to be translated (it's a lot): https://github.com/Shuffle/Shuffle/tree/master/functions/onprem
> 
> I see... though it would be easier... I'll probably take a look at it in a near future. Thanks for the guidance :)

Tell me when ;)

**Comment by frikky** [comment]
Continue in #970
