### ISSUE TITLE
Shuffle not starting.

### ISSUE THREAD

**Issue by bakhtawarw** [Shuffle/Shuffle#920]
**Describe the bug**
I installed shuffle by following the steps mentioned in installation guide but shuffle is unable to start. It keeps waiting for database to become available.
**To Reproduce**
1. git clone https://github.com/frikky/Shuffle
2. cd shuffle
3. sudo mkdir shuffle-database
4. sudo chown -R 1000:1000 shuffle-database
5. sudo docker compose up 
6. I changed the opensearch port to 9400 in docker compose file since 9200 port is already occupied by elasticsearch.
...

**Expected behavior**
Shuffle installed correctly and being able to login via admin account.

**Screenshots**
The login page keeps showing the following:
![image](https://user-images.githubusercontent.com/104062347/185546456-ff242464-8f7e-41db-976a-96d283057e2c.png)

DEBUG LOGS:

docker logs shuffle-backend

![image](https://user-images.githubusercontent.com/104062347/185548984-c8116fd1-5df4-4172-95a2-02a3afbc327a.png)

docker ps -a

![image](https://user-images.githubusercontent.com/104062347/185546939-29ed4f42-68fd-40d2-80a7-a360b049ae8f.png)

 
opensearch logs:

![image](https://user-images.githubusercontent.com/104062347/185548785-eba6b0c7-bea9-4eae-9ecb-07f18ecd4f8c.png)

**Comment by frikky** [comment]
Hey there! Could you please share ALL the logs in the shuffle-opensearch container? This is almost certainly a permission bug on the folder in use (chown -R 1000:1000 shuffle-database)

Thanks! :)

**Comment by bazinga-sicherheit** [comment]
Hey Frikky,
I am facing the same issue.

![image](https://user-images.githubusercontent.com/65133170/185925937-33798b73-7944-495c-a0c5-fcd8890291f1.png)
Open search log 
`root@localhost:/opt/Shuffle# docker logs 839bdaeaa118  --follow                                                                                                                                            
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin                                                                                                                         
OpenSearch Security Demo Installer                                                                                                                                                                         
 ** Warning: Do not use on production or public reachable systems **                                                                                                                                       
Basedir: /usr/share/opensearch                                                                                                                                                                             
OpenSearch install type: rpm/deb on NAME="Amazon Linux"                                                                                                                                                    
OpenSearch config dir: /usr/share/opensearch/config                                                                                                                                                        
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml                                                                                                                                        
OpenSearch bin dir: /usr/share/opensearch/bin                                                                                                                                                              
OpenSearch plugins dir: /usr/share/opensearch/plugins                                                                                                                                                      
OpenSearch lib dir: /usr/share/opensearch/lib                                                                                                                                                              
Detected OpenSearch Version: x-content-1.2.4                                                                                                                                                               
Detected OpenSearch Security Version: 1.2.4.0                                                                                                                                                              
                                                                                                                                                                                                           
### Success                                                                                                                                                                                                
### Execute this script now on all your nodes and then start all nodes                                                                                                                                     
### OpenSearch Security will be automatically initialized.                                                                                                                                                 
### If you like to change the runtime configuration                                                                                                                                                        
### change the files in ../securityconfig and execute:                                                                                                                                                     
"/usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh" -cd "/usr/share/opensearch/plugins/opensearch-security/securityconfig" -icl -key "/usr/share/opensearch/config/kirk-key.pem" -ce
rt "/usr/share/opensearch/config/kirk.pem" -cacert "/usr/share/opensearch/config/root-ca.pem" -nhnv                                                                                                        
### or run ./securityadmin_demo.sh                                                                                                                                                                         
### To use the Security Plugin ConfigurationGUI                                                                                                                                                            
### To access your secured cluster open https://<hostname>:<HTTP port> and log in with admin/admin.                                                                                                        
### (Ignore the SSL certificate warning because we installed self-signed demo certificates)                                                                                                                
Enabling OpenSearch Security Plugin                                                                                                                                                                        
Killing performance analyzer process 102                                                                                                                                                                   
OpenSearch exited with code 137                                                                                                                                                                            
Performance analyzer exited with code 143                                                                                                                                                                  
./opensearch-docker-entrypoint.sh: line 115:   101 Killed                  "$@" "${opensearch_opts[@]}"                                                                                                    
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin                                                                                                                         
OpenSearch Security Demo Installer                                                                                                                                                                         
 ** Warning: Do not use on production or public reachable systems **                                                                                                                                       
Basedir: /usr/share/opensearch                                                                                                                                                                             
OpenSearch install type: rpm/deb on NAME="Amazon Linux"                                                                                                                                                    
OpenSearch config dir: /usr/share/opensearch/config                                                                                                                                                        
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-1.2.4
Detected OpenSearch Security Version: 1.2.4.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
Killing performance analyzer process 33
OpenSearch exited with code 137
Performance analyzer exited with code 143
./opensearch-docker-entrypoint.sh: line 115:    32 Killed                  "$@" "${opensearch_opts[@]}"
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-1.2.4
Detected OpenSearch Security Version: 1.2.4.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
./opensearch-docker-entrypoint.sh: line 115:    32 Killed                  "$@" "${opensearch_opts[@]}"
Killing performance analyzer process 33
OpenSearch exited with code 137
Performance analyzer exited with code 143
Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin
OpenSearch Security Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Basedir: /usr/share/opensearch
OpenSearch install type: rpm/deb on NAME="Amazon Linux"
OpenSearch config dir: /usr/share/opensearch/config
OpenSearch config file: /usr/share/opensearch/config/opensearch.yml
OpenSearch bin dir: /usr/share/opensearch/bin
OpenSearch plugins dir: /usr/share/opensearch/plugins
OpenSearch lib dir: /usr/share/opensearch/lib
Detected OpenSearch Version: x-content-1.2.4
Detected OpenSearch Security Version: 1.2.4.0
/usr/share/opensearch/config/opensearch.yml seems to be already configured for Security. Quit.
Enabling OpenSearch Security Plugin
Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.FileAlreadyExistsException: /usr/share/opensearch/config/opensearch.keystore.tmp
Likely root cause: java.nio.file.FileAlreadyExistsException: /usr/share/opensearch/config/opensearch.keystore.tmp
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) `

Shuffle back-end log
`root@localhost:/opt/Shuffle# docker logs 129e231d9549  --follow                                                                                                                                            
2022/08/22 12:47:40 [DEBUG] Starting Shuffle backend - initializing database connection                                                                                                                    
2022/08/22 12:47:40 [DEBUG] SKIPPING SSL verification with Opensearch                                                                                                                                      
2022/08/22 12:47:40 [ERROR] Failed setting up Opensearch: dial tcp 172.20.0.2:9200: connect: connection refused                                                                                            
2022/08/22 12:47:40 [ERROR] Error in initial database connection. Retrying in 5 seconds. dial tcp 172.20.0.2:9200: connect: connection refused                                                             
2022/08/22 12:47:45 [DEBUG] SKIPPING SSL verification with Opensearch                                                          `
Shuffle-orborus log
`root@localhost:/opt/Shuffle# docker logs 4d82dad3c7f2                                                                                                                                                      
2022/08/22 12:47:40 [WARNING] RUNNING_MODE not set - defaulting to Docker (NOT Kubernetes).                                                                                                                
2022/08/22 12:47:40 [DEBUG] Set containerId network to 4d82dad3c7f259def59227eed1520280249756a2729e32077495d080c9ee0b88                                                                                    
2022/08/22 12:47:40 [INFO] Started with containerId "4d82dad3c7f259def59227eed1520280249756a2729e32077495d080c9ee0b88"                                                                                     
2022/08/22 12:47:40 [INFO] Setting up execution environment                                                                                                                                                
2022/08/22 12:47:40 [INFO] Running with timezone Europe/Amsterdam                                                                                                                                          
2022/08/22 12:47:40 [DEBUG] Running docker with default socket /var/run/docker.sock                                                                                                                        
2022/08/22 12:47:40 [INFO] Looking for old containers (zombies)                                                                                                                                            
2022/08/22 12:47:40 [INFO] Baseimage: frikky, Workertimeout: 600                                                                                                                                           
2022/08/22 12:47:40 [INFO] Should STOP 0 containers.                                                                                                                                                       
2022/08/22 12:47:40 [INFO] Should REMOVE 0 containers.                                                                                                                                                     
2022/08/22 12:47:40 [INFO] Running towards http://shuffle-backend:5001 (BASE_URL) with environment name Shuffle                                                                                            
2022/08/22 12:47:40 [INFO] Setting up Docker environment. Downloading worker and App SDK!                                                                                                                  
2022/08/22 12:47:40 [WARNING] SHUFFLE_APP_SDK_VERSION not defined. Defaulting to 0.8.97                                                                                                                    
2022/08/22 12:47:40 [DEBUG] Setting swarm config to "runn". Default is empty.                                                                                                                              
2022/08/22 12:47:40 [DEBUG] Pulling image frikky/shuffle:app_sdk                                                                                                                                           
{"status":"Pulling from frikky/shuffle","id":"app_sdk"}                                                                                                                                                    
{"status":"Digest: sha256:8345517a8ff3fb0409214c160e72177b243c27fbd7e94d2fa65bf49ed415c1fa"}                                                                                                               
{"status":"Status: Image is up to date for frikky/shuffle:app_sdk"}                                                                                                                                        
2022/08/22 12:47:41 [DEBUG] Successfully downloaded and built frikky/shuffle:app_sdk                                                                                                                       
2022/08/22 12:47:41 [DEBUG] Pulling image ghcr.io/frikky/shuffle-app_sdk:0.8.97                                                                                                                            
{"status":"Pulling from frikky/shuffle-app_sdk","id":"0.8.97"}                                                                                                                                             
{"status":"Digest: sha256:ddb1b7ba3582da4b6ea1a1120760e385178026c4ce69821fa74ec6cb6d3a1568"}                                                                                                               
{"status":"Status: Image is up to date for ghcr.io/frikky/shuffle-app_sdk:0.8.97"}                                                                                                                         
2022/08/22 12:47:41 [DEBUG] Successfully downloaded and built ghcr.io/frikky/shuffle-app_sdk:0.8.97                                                                                                        
2022/08/22 12:47:41 [DEBUG] Pulling image ghcr.io/frikky/shuffle-worker:latest                                                                                                                             
{"status":"Pulling from frikky/shuffle-worker","id":"latest"}                                                                                                                                              
{"status":"Digest: sha256:c529c005b2d193617ea147d2854541b97ccb034eb6975a159a4ebd6436c2610c"}                                                                                                               
{"status":"Status: Image is up to date for ghcr.io/frikky/shuffle-worker:latest"}                                                                                                                          
2022/08/22 12:47:42 [DEBUG] Successfully downloaded and built ghcr.io/frikky/shuffle-worker:latest                                                                                                         
2022/08/22 12:47:42 [INFO] Finished configuring docker environment                                                                                                                                         
2022/08/22 12:47:42 [INFO] Waiting for executions at http://shuffle-backend:5001/api/v1/workflows/queue with Environment Shuffle                                                                           
2022/08/22 12:47:42 [WARNING] Failed making request: Get "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.20.0.3:5001: connect: connection refused                                       
2022/08/22 12:47:45 [WARNING] Failed making request: Get "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.20.0.3:5001: connect: connection refused                                       
2022/08/22 12:47:48 [WARNING] Failed making request: Get "http://shuffle-backend:5001/api/v1/workflows/queue": dial tcp 172.20.0.3:5001: connect: connection refused  `

**Comment by frikky** [comment]
Hey! Could you try changing Opensearch in docker-compose.yml to use version 2? Like this:

![image](https://user-images.githubusercontent.com/5719530/185954216-88782850-2cb7-449f-8b81-a2910041bff7.png)

Please tell us if it persists or not :)

**Comment by bazinga-sicherheit** [comment]
Hey,
I changed the opensearch version but, same thing is happening. I deployed fresh image from the linode. 
![image](https://user-images.githubusercontent.com/65133170/185959602-9938d8aa-208b-48d7-ab47-e5aea4036ec5.png)
docker ps
![image](https://user-images.githubusercontent.com/65133170/185961248-05ed3618-d583-4df3-854e-e8ce38ce12b4.png)
It doesn't persist. 
![image](https://user-images.githubusercontent.com/65133170/185961885-5b3cb66e-9bae-43ad-bc50-1ab6db7b7700.png)
Thanks for the response. Would you need all logs?

**Comment by frikky** [comment]
Logs are always nice to have - thanks

**Comment by bakhtawarw** [comment]
> Hey there! Could you please share ALL the logs in the shuffle-opensearch container? This is almost certainly a permission bug on the folder in use (chown -R 1000:1000 shuffle-database)
> 
> Thanks! :)

Hi, it's working now. The change of opensearch port from 9200 to 9400 was hindering it's proper functioning. I created a new vm and deployed shuffle with the default opensearch port 9200. It's working perfectly fine now. Thank you!
